### ISSUE TITLE
file with .sdf of MOFs failed to calculate fingerprint and descriptors by Padelpy (verasion 0.1.11)

### ISSUE THREAD

**Issue by shenglisa** [ECRL/PaDELPy#37]

**Comment by shenglisa** [comment]
excuesme, recently i have calculated the fingerprints and descriptors of MOFs by Padelpy (verasion 0.1.11), but it occured errors , as shown below(Traceback (most recent call last):
  File "test.py", line 57, in <module>
    padeldescriptor(mol_dir = path, d_file = output_name, fingerprints=True, retainorder=True,     				detectaromaticity=False, threads=4)
  File "/home/lisa/.local/lib/python3.8/site-packages/padelpy/wrapper.py", line 157, in padeldescriptor
    raise **RuntimeError**('PaDEL-Descriptor encountered an error: {}'.format(
RuntimeError: PaDEL-Descriptor encountered an error: 7月 16, 2022 1:56:08 下午 libpadeldescriptor.CDK_Fingerprint run
严重: Fingerprinter error
org.openscience.cdk.exception.CDKException: org.openscience.cdk.exception.CDKException: Timeout for AllringsFinder exceeded
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.initializeMolecule(SMARTSQueryTool.java:363)
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.matches(SMARTSQueryTool.java:214)
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.matches(SMARTSQueryTool.java:189)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter$CountSubstructures.countSubstructure(PubchemFingerprinter.java:312)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter.countSubstructures(PubchemFingerprinter.java:1099)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter._generateFp(PubchemFingerprinter.java:323)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter.generateFp(PubchemFingerprinter.java:330)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter.getFingerprint(PubchemFingerprinter.java:122)
	at libpadeldescriptor.CDK_Fingerprint.run(Unknown Source)
	at libpadeldescriptor.libPaDELDescriptorWorker.DoJob(Unknown Source)
	at libpadeljobs.Worker.run(Worker.java:46)
Caused by: org.openscience.cdk.exception.CDKException: Timeout for AllringsFinder exceeded
	at org.openscience.cdk.ringsearch.AllRingsFinder.checkTimeout(AllRingsFinder.java:414)
	at org.openscience.cdk.ringsearch.AllRingsFinder.remove(AllRingsFinder.java:275)
	at org.openscience.cdk.ringsearch.AllRingsFinder.doSearch(AllRingsFinder.java:202)
	at org.openscience.cdk.ringsearch.AllRingsFinder.findAllRingsInIsolatedRingSystem(AllRingsFinder.java:174)
	at org.openscience.cdk.ringsearch.AllRingsFinder.findAllRings(AllRingsFinder.java:136)
	at org.openscience.cdk.ringsearch.AllRingsFinder.findAllRings(AllRingsFinder.java:117)
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.initializeMolecule(SMARTSQueryTool.java:360)
	... 10 more)

Below is the SDF file of MOF, could u tell me why?

ABEXOW_clean
 OpenBabel07132219403D

144158  0  0  1  0  0  0  0  0999 V2000
    9.5087    7.9092   12.6259 Pr  0  0  0  0  0  0  0  0  0  0  0  0
    4.2081    5.7270   16.7951 Pr  0  0  0  0  0  0  0  0  0  0  0  0
    1.4993    4.0928    2.8894 Pr  0  0  0  0  0  0  0  0  0  0  0  0
    6.7999    6.2750    7.0586 Pr  0  0  0  0  0  0  0  0  0  0  0  0
    7.0033    1.9082   12.6259 Pr  0  0  0  0  0  0  0  0  0  0  0  0
    1.2959   11.7280   16.7951 Pr  0  0  2  0  0  0  0  0  0  0  0  0
    4.0047   10.0938    2.8894 Pr  0  0  0  0  0  0  0  0  0  0  0  0
    9.7121    0.2740    7.0586 Pr  0  0  2  0  0  0  0  0  0  0  0  0
    7.1673    6.0970   14.7333 H   0  0  0  0  0  0  0  0  0  0  0  0
    8.4618    9.1287   17.8353 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.4266    7.2204   14.7936 H   0  0  0  0  0  0  0  0  0  0  0  0
   10.9420    2.9381   14.5755 H   0  0  0  0  0 15  0  0  0  0  0  0
    3.8407    5.9050    4.9968 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.5462    2.8733    8.0988 H   0  0  0  0  0  0  0  0  0  0  0  0
    9.5814    4.7816    5.0571 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0660    9.0639    4.8390 H   0  0  0  0  0 15  0  0  0  0  0  0
    9.3447    0.0960   14.7333 H   0  0  0  0  0  0  0  0  0  0  0  0
    8.0502    3.1277   17.8353 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.0774    1.2194   14.7936 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.5700    8.9391   14.5755 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.6633   11.9060    4.9968 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.9578    8.8743    8.0988 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.9306   10.7826    5.0571 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.4380    3.0629    4.8390 H   0  0  0  0  0  0  0  0  0  0  0  0
    7.4040    6.7547   15.3467 C   0  0  0  0  0  3  0  0  0  0  0  0
    7.0044    7.8061   17.3271 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1734    8.5406   17.1752 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.8879    8.3690   16.0185 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.0591    9.2595   15.6621 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.0896    8.0329   18.5110 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1195    6.3431   14.7644 C   0  0  0  0  0  3  0  0  0  0  0  0
    1.3881    4.1563   15.3291 C   0  0  1  0  0  3  0  0  0  0  0  0
    0.2290    3.8178   14.6417 C   0  0  0  0  0  1  0  0  0  0  0  0
   10.5545    4.8632   14.0692 C   0  0  0  0  0  3  0  0  0  0  0  0
    9.2401    4.6268   13.3293 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2390    3.0833   16.0107 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.5479    4.6028    0.3466 C   0  0  0  0  0  1  0  0  0  0  0  0
    2.2027    5.2269   19.3523 C   0  0  0  0  0  1  0  0  0  0  0  0
    3.6040    5.2473    5.6102 C   0  0  0  0  0  3  0  0  0  0  0  0
    4.0036    4.1959    7.5906 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8346    3.4614    7.4387 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1201    3.6330    6.2820 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9489    2.7425    5.9256 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.9184    3.9691    8.7745 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.8885    5.6589    5.0279 C   0  0  0  0  0  3  0  0  0  0  0  0
    9.6199    7.8457    5.5926 C   0  0  1  0  0  3  0  0  0  0  0  0
   10.7790    8.1842    4.9052 C   0  0  0  0  0  1  0  0  0  0  0  0
    0.4535    7.1388    4.3327 C   0  0  0  0  0  3  0  0  0  0  0  0
    1.7679    7.3752    3.5928 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.7690    8.9187    6.2742 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.4601    7.3992   10.0831 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.8053    6.7751    9.6158 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.1080    0.7537   15.3467 C   0  0  0  0  0  3  0  0  0  0  0  0
    9.5076    1.8051   17.3271 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.3386    2.5396   17.1752 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.6241    2.3680   16.0185 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.4529    3.2585   15.6621 C   0  0  2  0  0  3  0  0  0  0  0  0
   10.4224    2.0319   18.5110 C   0  0  0  0  0  3  0  0  0  0  0  0
    4.3845    0.3421   14.7644 C   0  0  0  0  0  3  0  0  0  0  0  0
    4.1159   10.1573   15.3291 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2750    9.8188   14.6417 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9575   10.8642   14.0692 C   0  0  0  0  0  3  0  0  0  0  0  0
    7.2719   10.6278   13.3293 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.2650    9.0843   16.0107 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.9561   10.6038    0.3466 C   0  0  0  0  0  1  0  0  0  0  0  0
    3.3013   11.2279   19.3523 C   0  0  0  0  0  1  0  0  0  0  0  0
    1.9000   11.2483    5.6102 C   0  0  0  0  0  3  0  0  0  0  0  0
    1.5004   10.1969    7.5906 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.6694    9.4624    7.4387 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.3839    9.6340    6.2820 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.5551    8.7435    5.9256 C   0  0  2  0  0  3  0  0  0  0  0  0
    0.5856    9.9701    8.7745 C   0  0  0  0  0  3  0  0  0  0  0  0
    6.6235   11.6599    5.0279 C   0  0  0  0  0  3  0  0  0  0  0  0
    6.8921    1.8447    5.5926 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7330    2.1832    4.9052 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0505    1.1378    4.3327 C   0  0  0  0  0  3  0  0  0  0  0  0
    3.7361    1.3742    3.5928 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.7430    2.9177    6.2742 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.0519    1.3982   10.0831 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.7067    0.7741    9.6158 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.5048    7.4712   15.0896 N   0  0  0  0  0  0  0  0  0  0  0  0
    6.6180    6.9120   16.4138 N   0  0  0  0  0  0  0  0  0  0  0  0
   11.0036    6.1138   14.0809 N   0  0  0  0  0  1  0  0  0  0  0  0
    1.8350    5.4309   15.4070 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.5032    4.5308    5.3531 N   0  0  0  0  0  0  0  0  0  0  0  0
    4.3900    5.0900    6.6773 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0044    5.8882    4.3444 N   0  0  0  0  0  1  0  0  0  0  0  0
    9.1730    6.5711    5.6705 N   0  0  0  0  0  0  0  0  0  0  0  0
    8.0072    1.4702   15.0896 N   0  0  0  0  0  0  0  0  0  0  0  0
    9.8940    0.9110   16.4138 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.5084    0.1128   14.0809 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.6690   11.4319   15.4070 N   0  0  0  0  0  2  0  0  0  0  0  0
    3.0008   10.5318    5.3531 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.1140   11.0910    6.6773 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.4996   11.8892    4.3444 N   0  0  0  0  0  0  0  0  0  0  0  0
    7.3390    0.5701    5.6705 N   0  0  0  0  0  2  0  0  0  0  0  0
   10.5159    9.1539   14.4957 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.4477   10.0637   16.5482 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0450    7.3044   18.5558 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.4309    8.8803   19.3133 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.7117    5.5881   12.7198 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.7470    3.4674   13.4539 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.2969    3.4398   16.5579 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.8251    1.9059   15.9270 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.4891    4.5740   18.9803 O   0  0  0  0  0  1  0  0  0  0  0  0
    3.5886    4.1743    1.5208 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.2456    5.8726   18.2735 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.2175    5.0576    0.6173 O   0  0  0  0  0  1  0  0  0  0  0  0
    0.4921    2.8481    4.7592 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.5603    1.9383    6.8117 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.9630    4.6976    8.8193 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.5771    3.1217    9.5768 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.2963    6.4139    2.9833 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.2610    8.5346    3.7174 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.7111    8.5622    6.8214 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.1829   10.0961    6.1905 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.5189    7.4280    9.2438 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.4194    7.8277   11.2573 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.7624    6.1294    8.5370 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.7905    6.9444   10.3538 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.9961    3.1529   14.4957 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.0643    4.0627   16.5482 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4590    1.3034   18.5558 O   0  0  0  0  0 15  0  0  0  0  0  0
   10.0811    2.8793   19.3133 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.8003   11.5891   12.7198 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.7650    9.4684   13.4539 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.2071    9.4408   16.5579 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.6789    7.9069   15.9270 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.0149   10.5750   18.9803 O   0  0  0  0  0  1  0  0  0  0  0  0
    1.9154   10.1753    1.5208 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.2584   11.8736   18.2735 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.2865   11.0586    0.6173 O   0  0  0  0  0  1  0  0  0  0  0  0
    5.0119    8.8491    4.7592 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.9437    7.9393    6.8117 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.5490   10.6986    8.8193 O   0  0  0  0  0 15  0  0  0  0  0  0
    0.9269    9.1227    9.5768 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.2077    0.4129    2.9833 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.2430    2.5336    3.7174 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.8009    2.5612    6.8214 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.3291    4.0951    6.1905 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9931    1.4270    9.2438 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.0926    1.8267   11.2573 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.7496    0.1284    8.5370 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.7215    0.9434   10.3538 O   0  0  0  0  0  0  0  0  0  0  0  0
  1101  1  0  0  0  0
  1126  1  0  0  0  0
  1 97  1  0  0  0  0
  1 81  1  0  0  0  0
  2107  1  0  0  0  0
  2 99  1  0  0  0  0
  2105  1  0  0  0  0
  3113  1  0  0  0  0
  3138  1  0  0  0  0
  3109  1  0  0  0  0
  3 85  1  0  0  0  0
  4119  1  0  0  0  0
  4111  1  0  0  0  0
  4117  1  0  0  0  0
  5102  1  0  0  0  0
  5 91  1  0  0  0  0
  5121  1  0  0  0  0
  5 89  1  0  0  0  0
  6131  1  0  0  0  0
  6129  1  6  0  0  0
  7114  1  0  0  0  0
  7 95  1  0  0  0  0
  7133  1  0  0  0  0
  7 93  1  0  0  0  0
  8 96  1  6  0  0  0
  8143  1  0  0  0  0
  8141  1  0  0  0  0
  9 25  1  0  0  0  0
 13 39  1  0  0  0  0
 17 53  1  0  0  0  0
 20 61  1  0  0  0  0
 21 67  1  0  0  0  0
 24 75  1  0  0  0  0
 25 82  1  0  0  0  0
 26 30  1  0  0  0  0
 27 26  1  0  0  0  0
 27 10  1  0  0  0  0
 28 27  2  0  0  0  0
 29 28  1  0  0  0  0
 29 98  2  0  0  0  0
 30 99  1  0  0  0  0
 30100  2  0  0  0  0
 31 11  1  0  0  0  0
 31 84  2  0  0  0  0
 32 33  1  6  0  0  0
 32 84  1  0  0  0  0
 32 36  1  0  0  0  0
 34 83  1  0  0  0  0
 35102  1  0  0  0  0
 35 34  2  0  0  0  0
 36103  1  0  0  0  0
 37106  1  0  0  0  0
 39 86  1  0  0  0  0
 40 44  1  0  0  0  0
 41 40  1  0  0  0  0
 41 14  1  0  0  0  0
 42 41  2  0  0  0  0
 43 42  1  0  0  0  0
 43110  2  0  0  0  0
 44111  1  0  0  0  0
 44112  2  0  0  0  0
 45 15  1  0  0  0  0
 45 88  2  0  0  0  0
 46 47  1  6  0  0  0
 46 88  1  0  0  0  0
 46 50  1  0  0  0  0
 48 87  1  0  0  0  0
 49114  1  0  0  0  0
 49 48  2  0  0  0  0
 50115  1  0  0  0  0
 51118  1  0  0  0  0
 52 51  2  0  0  0  0
 52120  1  0  0  0  0
 53 90  1  0  0  0  0
 54 58  1  0  0  0  0
 55 54  1  0  0  0  0
 55 18  1  0  0  0  0
 56 55  2  0  0  0  0
 57121  1  6  0  0  0
 57 56  1  0  0  0  0
 57122  1  0  0  0  0
 58124  2  0  0  0  0
 59 19  1  0  0  0  0
 60 92  1  0  0  0  0
 60 64  2  0  0  0  0
 61 60  1  0  0  0  0
 62 61  2  0  0  0  0
 63126  1  0  0  0  0
 63 62  1  0  0  0  0
 64127  1  0  0  0  0
 65130  1  0  0  0  0
 67 94  1  0  0  0  0
 68 72  1  0  0  0  0
 69 68  1  0  0  0  0
 69 22  1  0  0  0  0
 70 69  2  0  0  0  0
 71133  1  6  0  0  0
 71 70  1  0  0  0  0
 71134  1  0  0  0  0
 72136  2  0  0  0  0
 73 23  1  0  0  0  0
 74 96  1  0  0  0  0
 74 78  2  0  0  0  0
 75 74  1  0  0  0  0
 76 75  2  0  0  0  0
 77138  1  0  0  0  0
 77 76  1  0  0  0  0
 78139  1  0  0  0  0
 79142  1  0  0  0  0
 80 79  2  0  0  0  0
 80144  1  0  0  0  0
 81 25  1  0  0  0  0
 81 28  1  0  0  0  0
 82 26  2  0  0  0  0
 85 39  1  0  0  0  0
 85 42  1  0  0  0  0
 86 40  2  0  0  0  0
 89 53  1  0  0  0  0
 89 56  1  0  0  0  0
 90 54  2  0  0  0  0
 91 59  2  0  0  0  0
 92  6  1  0  0  0  0
 93 67  1  0  0  0  0
 93 70  1  0  0  0  0
 94 68  2  0  0  0  0
 95 73  2  0  0  0  0
 97 29  1  0  0  0  0
101 35  1  0  0  0  0
103  2  1  0  0  0  0
104 36  2  0  0  0  0
106  3  1  0  0  0  0
107 38  1  0  0  0  0
108  3  1  0  0  0  0
109 43  1  0  0  0  0
113 49  1  0  0  0  0
115  4  1  0  0  0  0
116 50  2  0  0  0  0
117 51  1  0  0  0  0
118  1  1  0  0  0  0
119 52  1  0  0  0  0
120  1  1  0  0  0  0
122  2  1  0  0  0  0
125 63  2  0  0  0  0
127  6  1  0  0  0  0
128 64  1  0  0  0  0
128  2  1  0  0  0  0
130  7  1  0  0  0  0
131 66  1  0  0  0  0
132  7  1  0  0  0  0
134  4  1  0  0  0  0
137 77  2  0  0  0  0
139  8  1  0  0  0  0
140 78  1  0  0  0  0
140  4  1  0  0  0  0
141 79  1  0  0  0  0
142  5  1  0  0  0  0
143 80  1  0  0  0  0
144  5  1  0  0  0  0
M  END
$$$$

**Comment by tjkessler** [comment]
Hi @shenglisa,

I've never seen an error like that before, I'll have to punt the question to someone else. I can tell you, however, that this error originates in PaDEL-Descriptor's source code, not the PaDELPy wrapper.

Best,
Travis

**Comment by tjkessler** [comment]
**Triage (0.1.17):** Large / metal–organic frameworks are often outside what the bundled PaDEL/CDK path handles. Failures raise `RuntimeError` / empty results as today.

Documented in `API_STABILITY.md`. Closing as upstream / out of scope for the thin wrapper without an approved engine upgrade. Removed from active “help wanted” for padelpy-only fixes.
