### ISSUE TITLE
Padelpy broken on Python 3.12

### ISSUE THREAD

**Issue by meowcat** [ECRL/PaDELPy#50]
On Python 3.12, padelpy seems broken at 
https://github.com/ecrl/padelpy/blob/6b992b47ad54c4c8aac96a6aeb2d3a5b5556cafe/padelpy/functions.py#L63
```
conda create -n padel python=3
conda activate padel
conda install -c conda-forge padelpy
python
```

```
>>> from padelpy import from_smiles
>>>
>>> # calculate molecular descriptors for propane
>>> descriptors = from_smiles('CCC')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Software\Michele\miniconda3\envs\padel\Lib\site-packages\padelpy\functions.py", line 63, in from_smiles
    filename = timestamp + str(random.randint(1e8,1e9))
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\Michele\miniconda3\envs\padel\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\Michele\miniconda3\envs\padel\Lib\random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```

This works on 3.10, I haven't checked 3.11. Apparently some typeconversion rules were tightened. - But is there a reason not to use `tempfile.mkstemp` here?

**Comment by JacksonBurns** [comment]
I have resolved this in #53
